In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
import datetime as datetime
import warnings
warnings.filterwarnings('ignore')
import pandas

In [2]:
contents=pd.read_csv('../orga2_21/contents.csv',low_memory=False)

In [3]:
logs=pd.read_csv('../orga2_21/logs.csv',low_memory=False)

In [5]:
#cambiamos el formato de timestamp
logs.loc[:,'timestamp']=pd.to_datetime(logs['timestamp'],errors='coerce')

In [6]:
logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12188946 entries, 0 to 12188945
Data columns (total 9 columns):
 #   Column                Dtype
---  ------                -----
 0   item_id               int64
 1   timestamp             datetime64[ns, UTC]
 2   contributor_username  object
 3   contributor_id        float64
 4   contributor_ip        object
 5   comment               object
 6   logtype               object
 7   action                object
 8   title                 object
dtypes: datetime64[ns, UTC](1), float64(1), int64(1), object(6)
memory usage: 836.9+ MB

In [10]:
logs=logs.drop(['logtype','item_id'], axis=1)

In [11]:
logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12188946 entries, 0 to 12188945
Data columns (total 7 columns):
 #   Column                Dtype
---  ------                -----
 0   timestamp             datetime64[ns, UTC]
 1   contributor_username  object
 2   contributor_id        float64
 3   contributor_ip        object
 4   comment               object
 5   action                object
 6   title                 object
dtypes: datetime64[ns, UTC](1), float64(1), object(5)
memory usage: 651.0+ MB

In [13]:
logs.isnull().sum()

timestamp                      0
contributor_username      125253
contributor_id            125253
contributor_ip          12064770
comment                  6856012
action                         2
title                       2005
dtype: int64

*** 
***
 # Ejercicio 56
 #### Calcule la cantidad de acciones realizadas por usuarios según día de la semana.
***
***

In [14]:
logs_56=logs[['timestamp','action']]
logs_56.head()

                  timestamp  action
0 2004-12-23 07:10:09+00:00  delete
1 2004-12-23 07:14:09+00:00  delete
2 2004-12-23 07:26:10+00:00  delete
3 2004-12-23 07:55:09+00:00  delete
4 2004-12-23 08:02:22+00:00  delete

In [15]:
logs_56.dropna(subset=['action'], inplace=True)
logs_56.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12188944 entries, 0 to 12188945
Data columns (total 2 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  datetime64[ns, UTC]
 1   action     object
dtypes: datetime64[ns, UTC](1), object(1)
memory usage: 279.0+ MB

In [17]:
logs_56['timestamp'] = pd.to_datetime(logs_56['timestamp'])
logs_56['weekday'] = logs_56['timestamp'].dt.day_name()
logs_56.head()

                  timestamp  action   weekday
0 2004-12-23 07:10:09+00:00  delete  Thursday
1 2004-12-23 07:14:09+00:00  delete  Thursday
2 2004-12-23 07:26:10+00:00  delete  Thursday
3 2004-12-23 07:55:09+00:00  delete  Thursday
4 2004-12-23 08:02:22+00:00  delete  Thursday

In [18]:
logs_56=logs_56[['action','weekday']]
logs_56['cantidad']=1
logs_56.head()

   action   weekday  cantidad
0  delete  Thursday         1
1  delete  Thursday         1
2  delete  Thursday         1
3  delete  Thursday         1
4  delete  Thursday         1

In [19]:
logs_56=pd.pivot_table(logs_56,values='cantidad',columns='weekday',index='action',aggfunc=np.sum)
logs_56.fillna(0,inplace=True)
logs_56.head()

weekday,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
action,,,,,,,
add,368.0,276.0,295.0,325.0,486.0,205.0,231.0
addlink,97.0,12.0,21.0,0.0,4.0,4.0,3.0
autocreate,187680.0,206085.0,174712.0,188758.0,200243.0,206251.0,205335.0
block,46145.0,56257.0,31255.0,41517.0,55526.0,57094.0,54508.0
byemail,848.0,1010.0,744.0,668.0,1028.0,1082.0,1017.0

In [20]:
logs_56

weekday,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
action,,,,,,,
add,368.0,276.0,295.0,325.0,486.0,205.0,231.0
addlink,97.0,12.0,21.0,0.0,4.0,4.0,3.0
autocreate,187680.0,206085.0,174712.0,188758.0,200243.0,206251.0,205335.0
block,46145.0,56257.0,31255.0,41517.0,55526.0,57094.0,54508.0
byemail,848.0,1010.0,744.0,668.0,1028.0,1082.0,1017.0
change,3.0,2.0,4.0,4.0,0.0,6.0,2.0
create,821179.0,920683.0,730836.0,773304.0,917195.0,953054.0,949089.0
create2,3268.0,3667.0,2975.0,2966.0,3659.0,3954.0,3751.0
delete,332299.0,347485.0,309852.0,316602.0,361379.0,363906.0,364868.0
delete_redir,3834.0,4312.0,3798.0,3914.0,3895.0,3842.0,3530.0
deleteuser,1.0,0.0,0.0,0.0,0.0,0.0,0.0
event,137.0,129.0,159.0,151.0,161.0,142.0,108.0
failure,31.0,186.0,1.0,0.0,3.0,7.0,1.0
interwiki,18.0,9.0,19.0,3.0,26.0,21.0,12.0
merge,4.0,1.0,1.0,5.0,5.0,1.0,4.0
mergeuser,1.0,0.0,0.0,0.0,0.0,0.0,0.0
modify,583.0,568.0,578.0,551.0,632.0,588.0,692.0
move,91720.0,95901.0,97625.0,299688.0,92903.0,92088.0,90851.0
move_prot,348.0,372.0,317.0,953.0,398.0,294.0,398.0
move_redir,13237.0,15270.0,14267.0,14718.0,13643.0,14185.0,13880.0
new,0.0,1.0,0.0,0.0,1.0,2.0,0.0
newusers,10466.0,10885.0,8953.0,9464.0,11612.0,12064.0,11979.0
patrol,35105.0,34530.0,42358.0,42167.0,32348.0,36170.0,34747.0
profilesave,0.0,0.0,0.0,0.0,0.0,5.0,2.0
protect,12815.0,13467.0,11219.0,12545.0,13253.0,13415.0,14643.0
reblock,927.0,1311.0,1121.0,1121.0,960.0,1096.0,1163.0
remove,64.0,35.0,41.0,38.0,99.0,29.0,36.0
renameuser,2872.0,3045.0,2957.0,187067.0,2700.0,3014.0,2789.0
restore,5524.0,5920.0,5997.0,6219.0,6081.0,6050.0,6237.0
review,100.0,158.0,215.0,58.0,163.0,76.0,119.0
revision,3609.0,3883.0,3382.0,3215.0,4211.0,4231.0,4319.0
rights,517.0,544.0,442.0,690.0,498.0,546.0,537.0
selfadd,805.0,696.0,413.0,135.0,846.0,794.0,624.0
selfremove,68.0,94.0,39.0,23.0,82.0,79.0,58.0
send,2.0,3.0,6.0,3.0,2.0,3.0,0.0
skipbadns,2.0,20.0,0.0,1.0,1.0,11.0,8.0
skipnouser,2.0,168.0,1.0,0.0,3.0,5.0,2.0
thank,34267.0,36045.0,32323.0,33423.0,34782.0,35790.0,35318.0
unblock,504.0,570.0,517.0,459.0,562.0,588.0,623.0
undelete,2.0,1.0,0.0,0.0,0.0,0.0,0.0
unprotect,614.0,554.0,484.0,457.0,616.0,753.0,659.0
unreview,6.0,6.0,24.0,1.0,10.0,0.0,3.0
update,601.0,1086.0,758.0,687.0,678.0,783.0,1476.0
upload,2223.0,2297.0,2104.0,2416.0,2204.0,2278.0,2344.0
usergroups,2.0,0.0,1.0,0.0,0.0,1.0,0.0
whitelist,0.0,0.0,0.0,0.0,0.0,1.0,0.0

*** 
***
 # Ejercicio 58
 #### Observe una muestra aleatoria de los comentarios de las acciones realizadas por usuarios o ips antes de ser bloqueados. Observe otra muestra de comentarios de acciones de todos.
***
***

In [23]:
logs.action.unique()

array(['delete', 'block', 'upload', 'protect', 'restore', 'unblock',
       'unprotect', 'rights', 'move', 'move_redir', nan, 'renameuser',
       'newusers', 'create', 'create2', 'modify', 'patrol', 'autocreate',
       'usergroups', 'move_prot', 'reblock', 'event', 'revision',
       'interwiki', 'byemail', 'thank', 'add', 'update', 'remove',
       'selfadd', 'selfremove', 'review', 'failure', 'skipbadns', 'send',
       'unreview', 'skipnouser', 'profilesave', 'undelete', 'merge',
       'mergeuser', 'deleteuser', 'delete_redir', 'whitelist', 'change',
       'new', 'addlink'], dtype=object)

In [27]:
logs_58=logs[['comment','action','title']]
logs_58.head()

,comment,action,title
0,el contenido era: 'Si aprendés Pensamiento Cie...,delete,Verificacionismo
1,el contenido era: '{{destruir}}en algun lugar ...,delete,Rapunzel
2,el contenido era: '#REDIRECT [[Flash]]',delete,Macromedia Flash
3,Sin información de origen ni de licencia. Hay ...,delete,Archivo:Gnu head.png
4,Sustituida por [[commons:Image:Heckert_GNU.png]],delete,Archivo:Gnu-head-sm.jpg

In [28]:
logs_58=logs_58.loc[logs_58['action']=='block']
logs_58.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 342302 entries, 5 to 12188930
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   comment  333429 non-null  object
 1   action   342302 non-null  object
 2   title    341911 non-null  object
dtypes: object(3)
memory usage: 10.4+ MB

In [29]:
logs_58.dropna(subset=['comment','title'], inplace=True)
logs_58.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 333123 entries, 5 to 12188930
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   comment  333123 non-null  object
 1   action   333123 non-null  object
 2   title    333123 non-null  object
dtypes: object(3)
memory usage: 10.2+ MB

In [30]:
logs_58.head(10)

,comment,action,title
5,vandalismo grosero,block,Usuario:212.55.30.157
287,vandalismo grosero,block,Usuario:201.241.228.15
288,vandalismo en [[PlayStation]],block,Usuario:201.255.50.32
290,blanqueo de varios artículos,block,Usuario:84.122.0.158
313,spam sistemático de la web http://www.islamenl...,block,Usuario:81.192.12.93
451,Spam,block,Usuario:81.192.30.42
452,vandalismos varios,block,Usuario:80.58.3.239
471,vandalismo grosero,block,Usuario:200.28.184.131
487,vandalismo en [[Pantalla de cristal líquido]],block,Usuario:62.83.249.208
489,vandalismo en [[Josef Mengele]],block,Usuario:63.171.232.248

In [35]:
new = logs_58["title"].str.split(":", n = 1, expand = True)
#new[0]='usuario...
logs_58["users_id_ip"]= new[1]

logs_58.drop(columns =["title"], inplace = True)
logs_58.head()

                                               comment action     users_id_ip
5                                   vandalismo grosero  block   212.55.30.157
287                                 vandalismo grosero  block  201.241.228.15
288                      vandalismo en [[PlayStation]]  block   201.255.50.32
290                       blanqueo de varios artículos  block    84.122.0.158
313  spam sistemático de la web http://www.islamenl...  block    81.192.12.93

In [38]:
logs_58.users_id_ip.value_counts()

80.58.205.33         32
80.58.205.44         32
Antoine              32
80.58.205.46         31
80.58.205.43         31
                     ..
Jose-mola-3333333     1
186.168.242.145       1
195.168.109.60        1
201.236.110.139       1
190.192.202.30        1
Name: users_id_ip, Length: 292135, dtype: int64

### Nos quedamos con los comentarios del porque fueron bloqueados los usuarios por ultima vez

In [39]:
logs_58.drop_duplicates(subset=['users_id_ip'], keep='last',inplace=True)
logs_58.head()

                                               comment action     users_id_ip
5                                   vandalismo grosero  block   212.55.30.157
287                                 vandalismo grosero  block  201.241.228.15
288                      vandalismo en [[PlayStation]]  block   201.255.50.32
290                       blanqueo de varios artículos  block    84.122.0.158
313  spam sistemático de la web http://www.islamenl...  block    81.192.12.93

In [40]:
print(logs_58.shape)

(292135, 3)

In [41]:
logs_58.head(20)

                                                comment action     users_id_ip
5                                    vandalismo grosero  block   212.55.30.157
287                                  vandalismo grosero  block  201.241.228.15
288                       vandalismo en [[PlayStation]]  block   201.255.50.32
290                        blanqueo de varios artículos  block    84.122.0.158
313   spam sistemático de la web http://www.islamenl...  block    81.192.12.93
451                                                Spam  block    81.192.30.42
452                                  vandalismos varios  block     80.58.3.239
471                                  vandalismo grosero  block  200.28.184.131
487       vandalismo en [[Pantalla de cristal líquido]]  block   62.83.249.208
494                     vandalismo en [[Josef Mengele]]  block    200.119.39.9
524      Vandalismos en Madrid, Cataluña y Juanín Bravo  block     80.58.2.170
583                                vandalismo reiterado  block   200.30.128.70
1103                 vandalismo en [[Países Catalanes]]  block    213.4.128.41
1201      Vandalismo en [[Síndrome de la mano extraña]]  block   200.92.10.251
1490                                       spam en Pisa  block   217.133.8.229
1739                               Vandalismo reiterado  block  201.248.116.90
2090                                vandalismo Jozualdo  block  200.60.188.219
2155  eliminación de comentarios en páginas de discu...  block  200.112.75.198
2240                                               spam  block   213.60.17.248
2242                              vandalismo "gracioso"  block     80.58.47.44

In [43]:
muestraAleatoria = logs_58.sample(frac=0.125)
muestraAleatoria

,comment,action,users_id_ip
8340241,[[WP:VN|Cuenta creada para vandalizar]],block,Josele.616
3607778,[[Wikipedia:Vandalismo|Vandalismo]],block,Rochi1998
2399896,[[WP:VN|Vandalismo]],block,190.235.2.237
7608497,[[WP:VN|Vandalismo de páginas]],block,200.87.185.28
10417204,[[WP:NU|Viola la política de nombres de usuari...,block,Sflashjvawefksud
...,...,...,...
3919087,Proxy,block,110.139.24.116
7340334,[[WP:VN|Vandalismo de páginas]],block,213.96.251.204
4954456,[[WP:NAP|Intimidación/Acoso a usuarios]],block,201.240.187.124
2747364,[[WP:VN|Vandalismo de páginas]],block,80.25.232.173
7949489,[[WP:NU|Viola la política de nombres de usuari...,block,Tuputamadre1002318483

*** 
***
 # Ejercicio 55
 #### La cantidad promedio de modificaciones históricas que tuvieron los ítems cuya última versión fue editada por un usuario registrado o no registrado.
***
***

In [47]:
import re 
logs.title.str.count("Titulo:|Title:",re.I).sum()

9.0

In [22]:
a=logs[logs.title.str.contains('title:|Title:|titulo:|Titulo:')]
a

,item_id,timestamp,contributor_username,contributor_id,contributor_ip,comment,logtype,action,title
672063,672064,2007-03-29T19:11:58Z,Dianai,18218.0,NaN,el contenido era: «Titulo: Media nocheautor: ...,delete,delete,Titulo: Media noche. autor: José Vicente Abreu
4499463,6019198,2012-10-13T11:02:25Z,Dhidalgo,272716.0,NaN,NaN,move,move,Intitle:vineyard
4531486,6065216,2012-10-30T23:16:24Z,Dhidalgo,272716.0,NaN,NaN,move,move,Intitle:Montaño
4558985,6105441,2012-11-15T18:02:13Z,Pólux,265898.0,NaN,[[WP:BR#Redirecciones|R3]]: redirección innece...,delete,delete,Intitle:vineyard
4558987,6105443,2012-11-15T18:02:28Z,Pólux,265898.0,NaN,[[WP:BR#Redirecciones|R3]]: redirección innece...,delete,delete,Intitle:Montaño
4613296,6185563,2012-12-19T18:07:48Z,Dhidalgo,272716.0,NaN,NaN,move,move,Intitle:Bauru
4621443,6197747,2012-12-26T22:12:01Z,BlackBeast,325108.0,NaN,[[WP:BR#R3|Redirección automática]]: el conten...,delete,delete,Intitle:Bauru
5076745,6892369,2013-09-09T23:45:52Z,Azylber,1227021.0,NaN,error de tipeo,move,move,Intitle:Oscar Lescano
5137522,6972015,2013-10-14T02:10:49Z,Taichi,32328.0,NaN,borrado rápido; el contenido era «{{Destruir|R...,delete,delete,Intitle:Oscar Lescano